spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/freelancePlatformDb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update